-- Florist Studio v4.0 — complete Supabase setup for the current app
-- Safe to run more than once. Run in Dashboard > SQL Editor.

begin;

create table if not exists public.workspace_snapshots (
  user_id uuid primary key references auth.users(id) on delete cascade,
  workspace jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  business_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.privacy_audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  subject_ref text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists workspace_snapshots_set_updated_at on public.workspace_snapshots;
create trigger workspace_snapshots_set_updated_at
before update on public.workspace_snapshots
for each row execute function public.set_updated_at();

drop trigger if exists user_profiles_set_updated_at on public.user_profiles;
create trigger user_profiles_set_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at();

alter table public.workspace_snapshots enable row level security;
alter table public.user_profiles enable row level security;
alter table public.privacy_audit_log enable row level security;

revoke all on public.workspace_snapshots, public.user_profiles, public.privacy_audit_log from anon;
grant select, insert, update, delete on public.workspace_snapshots to authenticated;
grant select, insert, update, delete on public.user_profiles to authenticated;
grant select, insert, delete on public.privacy_audit_log to authenticated;
grant usage, select on sequence public.privacy_audit_log_id_seq to authenticated;

drop policy if exists "workspace_select_own" on public.workspace_snapshots;
create policy "workspace_select_own" on public.workspace_snapshots for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "workspace_insert_own" on public.workspace_snapshots;
create policy "workspace_insert_own" on public.workspace_snapshots for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "workspace_update_own" on public.workspace_snapshots;
create policy "workspace_update_own" on public.workspace_snapshots for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "workspace_delete_own" on public.workspace_snapshots;
create policy "workspace_delete_own" on public.workspace_snapshots for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "profiles_select_own" on public.user_profiles;
create policy "profiles_select_own" on public.user_profiles for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "profiles_insert_own" on public.user_profiles;
create policy "profiles_insert_own" on public.user_profiles for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "profiles_update_own" on public.user_profiles;
create policy "profiles_update_own" on public.user_profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "profiles_delete_own" on public.user_profiles;
create policy "profiles_delete_own" on public.user_profiles for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "audit_select_own" on public.privacy_audit_log;
create policy "audit_select_own" on public.privacy_audit_log for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "audit_insert_own" on public.privacy_audit_log;
create policy "audit_insert_own" on public.privacy_audit_log for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "audit_delete_own" on public.privacy_audit_log;
create policy "audit_delete_own" on public.privacy_audit_log for delete to authenticated using ((select auth.uid()) = user_id);

-- Private image bucket, ready for a later migration away from base64 workspace images.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('florist-images', 'florist-images', false, 10485760, array['image/jpeg','image/png','image/webp','image/heic','image/heif'])
on conflict (id) do update set public=false, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "images_select_own" on storage.objects;
create policy "images_select_own" on storage.objects for select to authenticated
using (bucket_id='florist-images' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "images_insert_own" on storage.objects;
create policy "images_insert_own" on storage.objects for insert to authenticated
with check (bucket_id='florist-images' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "images_update_own" on storage.objects;
create policy "images_update_own" on storage.objects for update to authenticated
using (bucket_id='florist-images' and (storage.foldername(name))[1]=(select auth.uid())::text)
with check (bucket_id='florist-images' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "images_delete_own" on storage.objects;
create policy "images_delete_own" on storage.objects for delete to authenticated
using (bucket_id='florist-images' and (storage.foldername(name))[1]=(select auth.uid())::text);

commit;
